# Generated by Django 4.1.3 on 2022-12-12 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='amount',
            field=models.IntegerField(default=1, help_text='Enter number of times it should be taken a day', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='Enter name of medicine', max_length=50),
        ),
    ]
