# Generated by Django 4.1.3 on 2023-01-07 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_amount_alter_medicine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='amount',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(default=1, help_text='Enter dosage of the medicine', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='medicine',
            name='times',
            field=models.IntegerField(default=1, help_text='Enter number of times it should be taken a day', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
